### ISSUE TITLE
MapUnitPoints

### ISSUE THREAD

**Issue by rcrow** [usgs/gems-tools-arcmap#33]
It seems that MapUnitPoints can only be added in the 10 (not the 105) version of the New Database tool.

**Comment by rhaugerud** [comment]
This most likely reflected failure to save the new .tbx in version 10-compatible format.  "Save As" doesn't work if the file already exists, but ArcMap offers no warnings--you have to check timestamps to see that nothing happened.  

There have been several updates to the .tbx files since July 2019, so I suspect this issue is moot. I'm closing it.
