### ISSUE TITLE
Relationship Classes Tool - Issues

### ISSUE THREAD

**Issue by rbeard09** [usgs/gems-tools-arcmap#38]
I am attempting to use the Relationships Classes Tool. 

The tool as downloaded references the script : C:\Users\rhaugerud\Code\GeMS_Tools\Scripts\Relationships.py

This script does not exist. 
The tool should reference - \GeMS_Tools-master\Scripts\GeMS_RelationshipClasses1_Arc10.py 

When the proper source is set it functions as expected. 

In addition, the ArcPro tool fails with the attached message: 
 
Thank you for all your work on these tools. 

![ArcPro Relationship Class Tool](https://user-images.githubusercontent.com/56136599/67802667-da62ad00-fa48-11e9-824c-ad9d8351bf6e.jpg)

**Comment by ethoms-usgs** [comment]
Thank you for finding that bug. That has to be changed in the .tbx file. I will try to get to it soon.

The other issue, because it relates to the Python 3 version, does not pertain to this repo. It belongs here:
https://github.com/ethoms-usgs/GeMS_Tools

I will start an issue over there and work on it.

**Comment by ethoms-usgs** [comment]
I just checked and the tool runs correctly in ArcMap and ArcGIS Pro. I will close this issue.
