### ISSUE TITLE
Wiki doesn't display formatting

### ISSUE THREAD

**Issue by curtvprice** [usgs/gems-tools-arcmap#57]
Hi Evan!

Lots of great stuff here on the wiki! Looking to see if maybe we can use GeMS for some undigitized quads in South Dakota with students.

Doc links like https://raw.githubusercontent.com/wiki/usgs/gems-resources/GeMS_ToolsDocumentation.md

are coming up in text, not in markup. Is by design?

**Comment by rhaugerud** [comment]
Curtis-

https://github.com/usgs/gems-tools-arcmap/wiki/GeMS_ToolsDocumentation is showing as formatted text for me.

How (or why) did you get to the URL https://raw.githubusercontent.com/wiki/usgs/gems-resources/GeMS_ToolsDocumentation.md ?

cheers,

Ralph
________________________________

**Comment by ethoms-usgs** [comment]
Ralph, 
turns out there is an odd characteristic of the way GitHub reads markdown. If you compose a nest of related .md records locally (I have been using Atom - it's really great), you need to write ".md" at the end of the link, but GitHub re-directs that to the raw view. If you want GitHub to display the rendered markdown, you just write the name of the page like an anchor, with no .md extension. Curtis may have hit one of the paths I wrote in Atom and hadn't changed before pushing. I went through the links on that page the other day and fixed them all (I think).

I will close this issue and we can re-open it if necessary.
